/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example;


import org.example.GUI.ClockFrame;

import java.awt.*;
import java.io.IOException;

public class App {


    public static void main(String[] args) throws FontFormatException, IOException {

        ClockFrame clock = new ClockFrame();
        clock.setVisible(true); }
}
